#   server:
#   port: 因为会启动多个 product-data-service, 所以端口号由用户自动设置，推荐 8001,8002,8003

spring:
  application:
    name: product-data-service
  zipkin:
    base-url: http://localhost:9411
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=utf-8
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
