spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
          uri: https://github.com/jiangtingfeng/springcloudconfig-1/
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/